import { ExerciseDefinition, ExercisePlanItem, Muscle } from "@/lib/types";

const createExercise = (definition: ExerciseDefinition): ExerciseDefinition => definition;

export const EXERCISE_NAME_ALIASES: Record<string, string> = {
  平板卧推: "平板杠铃卧推",
  哑铃平板卧推: "哑铃卧推",
  上斜器械推胸: "器械推胸",
  侧平举: "哑铃侧平举",
  绳索面拉: "面拉",
  高位下拉: "宽握下拉",
  分腿蹲: "保加利亚分腿蹲",
  单腿硬拉: "单腿罗马尼亚硬拉",
  髋外展: "坐姿髋外展",
};

export const exerciseLibrary: Record<Muscle, ExerciseDefinition[]> = {
  胸: [
    createExercise({ name: "平板杠铃卧推", musclePrimary: "胸", muscleSecondary: ["三头", "肩前束"], movement: "推", pattern: "水平推", equipment: "杠铃", type: "复合" }),
    createExercise({ name: "上斜杠铃卧推", musclePrimary: "胸", muscleSecondary: ["三头", "肩前束"], movement: "推", pattern: "水平推", equipment: "杠铃", type: "复合" }),
    createExercise({ name: "哑铃卧推", musclePrimary: "胸", muscleSecondary: ["三头", "肩前束"], movement: "推", pattern: "水平推", equipment: "哑铃", type: "复合" }),
    createExercise({ name: "上斜哑铃卧推", musclePrimary: "胸", muscleSecondary: ["三头", "肩前束"], movement: "推", pattern: "水平推", equipment: "哑铃", type: "复合" }),
    createExercise({ name: "俯卧撑", musclePrimary: "胸", muscleSecondary: ["三头", "肩前束"], movement: "推", pattern: "水平推", equipment: "徒手", type: "复合" }),
    createExercise({ name: "器械推胸", musclePrimary: "胸", muscleSecondary: ["三头"], movement: "推", pattern: "水平推", equipment: "器械", type: "复合" }),
    createExercise({ name: "蝴蝶机夹胸", musclePrimary: "胸", movement: "推", pattern: "夹胸", equipment: "器械", type: "孤立" }),
  ],
  肩: [
    createExercise({ name: "哑铃推肩", musclePrimary: "肩", muscleSecondary: ["三头"], movement: "推", pattern: "垂直推", equipment: "哑铃", type: "复合" }),
    createExercise({ name: "器械推肩", musclePrimary: "肩", muscleSecondary: ["三头"], movement: "推", pattern: "垂直推", equipment: "器械", type: "复合" }),
    createExercise({ name: "哑铃侧平举", musclePrimary: "肩", movement: "外展", pattern: "侧平举", equipment: "哑铃", type: "孤立" }),
    createExercise({ name: "绳索侧平举", musclePrimary: "肩", movement: "外展", pattern: "侧平举", equipment: "绳索", type: "孤立", unilateral: true }),
    createExercise({ name: "反向飞鸟", musclePrimary: "肩后束", muscleSecondary: ["背"], movement: "拉", pattern: "后束", equipment: "哑铃", type: "孤立" }),
    createExercise({ name: "面拉", musclePrimary: "肩后束", muscleSecondary: ["背"], movement: "拉", pattern: "后束", equipment: "绳索", type: "孤立" }),
  ],
  背: [
    createExercise({ name: "坐姿划船", musclePrimary: "背", muscleSecondary: ["二头"], movement: "拉", pattern: "水平拉", equipment: "器械", type: "复合" }),
    createExercise({ name: "器械划船", musclePrimary: "背", muscleSecondary: ["二头"], movement: "拉", pattern: "水平拉", equipment: "器械", type: "复合" }),
    createExercise({ name: "引体向上", musclePrimary: "背", muscleSecondary: ["二头"], movement: "拉", pattern: "垂直拉", equipment: "徒手", type: "复合" }),
    createExercise({ name: "宽握下拉", musclePrimary: "背", muscleSecondary: ["二头"], movement: "拉", pattern: "垂直拉", equipment: "器械", type: "复合" }),
    createExercise({ name: "单臂绳索下拉", musclePrimary: "背", muscleSecondary: ["二头", "核心"], movement: "拉", pattern: "垂直拉", equipment: "绳索", type: "复合", unilateral: true }),
    createExercise({ name: "窄握下拉", musclePrimary: "背", muscleSecondary: ["二头"], movement: "拉", pattern: "垂直拉", equipment: "器械", type: "复合" }),
    createExercise({ name: "对握下拉", musclePrimary: "背", muscleSecondary: ["二头"], movement: "拉", pattern: "垂直拉", equipment: "器械", type: "复合" }),
    createExercise({ name: "面拉", musclePrimary: "肩后束", muscleSecondary: ["背"], movement: "拉", pattern: "后束", equipment: "绳索", type: "孤立" }),
  ],
  臀腿: [
    createExercise({ name: "杠铃深蹲", musclePrimary: "臀腿", muscleSecondary: ["核心"], movement: "蹲", pattern: "膝主导", equipment: "杠铃", type: "复合" }),
    createExercise({ name: "史密斯深蹲", musclePrimary: "臀腿", movement: "蹲", pattern: "膝主导", equipment: "器械", type: "复合" }),
    createExercise({ name: "腿举", musclePrimary: "臀腿", movement: "蹲", pattern: "膝主导", equipment: "器械", type: "复合" }),
    createExercise({ name: "保加利亚分腿蹲", musclePrimary: "臀腿", movement: "蹲", pattern: "单腿", equipment: "哑铃", type: "复合", unilateral: true }),
    createExercise({ name: "坐姿腿屈伸", musclePrimary: "股四头", movement: "伸展", pattern: "孤立", equipment: "器械", type: "孤立" }),
    createExercise({ name: "坐姿腿弯举", musclePrimary: "腿后侧", movement: "弯曲", pattern: "孤立", equipment: "器械", type: "孤立" }),
    createExercise({ name: "俯卧腿弯举", musclePrimary: "腿后侧", movement: "弯曲", pattern: "孤立", equipment: "器械", type: "孤立" }),
    createExercise({ name: "罗马尼亚硬拉", musclePrimary: "臀腿", muscleSecondary: ["下背"], movement: "拉", pattern: "髋主导", equipment: "杠铃", type: "复合" }),
    createExercise({ name: "单腿罗马尼亚硬拉", musclePrimary: "臀腿", muscleSecondary: ["核心"], movement: "拉", pattern: "髋主导", equipment: "哑铃", type: "复合", unilateral: true }),
    createExercise({ name: "臀桥", musclePrimary: "臀", movement: "推", pattern: "髋主导", equipment: "杠铃", type: "复合" }),
    createExercise({ name: "坐姿髋外展", musclePrimary: "臀中肌", movement: "外展", pattern: "髋外展", equipment: "器械", type: "孤立" }),
  ],
};

export const defaultPlans: Record<Muscle, ExercisePlanItem[]> = {
  胸: [
    { name: "平板杠铃卧推", weight: "70", sets: "4", reps: "8", rest: "120", intensity: "RPE 8", progression: "做满后下次加 2.5kg" },
    { name: "上斜哑铃卧推", weight: "26", sets: "4", reps: "10", rest: "90", intensity: "RPE 8", progression: "全程保持肩胛稳定" },
    { name: "蝴蝶机夹胸", weight: "35", sets: "3", reps: "12", rest: "75", intensity: "RPE 7", progression: "顶峰停顿 1 秒" },
    { name: "器械推胸", weight: "45", sets: "3", reps: "10", rest: "75", intensity: "RPE 7", progression: "肩胛稳定后逐步加重" },
  ],
  肩: [
    { name: "哑铃推肩", weight: "20", sets: "4", reps: "10", rest: "90", intensity: "RPE 8", progression: "稳定上举再加重" },
    { name: "哑铃侧平举", weight: "10", sets: "4", reps: "15", rest: "60", intensity: "RPE 7", progression: "别借力，优先动作轨迹" },
    { name: "绳索侧平举", weight: "8", sets: "3", reps: "15", rest: "60", intensity: "RPE 7", progression: "单侧控制离心" },
    { name: "反向飞鸟", weight: "10", sets: "3", reps: "15", rest: "60", intensity: "RPE 7", progression: "感受后束发力" },
  ],
  背: [
    { name: "引体向上", weight: "0", sets: "4", reps: "8", rest: "120", intensity: "RPE 8", progression: "能做满就增加 1-2 次" },
    { name: "宽握下拉", weight: "65", sets: "4", reps: "10", rest: "90", intensity: "RPE 8", progression: "顶峰夹背后再还原" },
    { name: "单臂绳索下拉", weight: "25", sets: "3", reps: "12", rest: "75", intensity: "RPE 8", progression: "单侧做满后再小幅加重" },
    { name: "坐姿划船", weight: "60", sets: "4", reps: "10", rest: "90", intensity: "RPE 8", progression: "动作稳定后上调一档" },
    { name: "面拉", weight: "20", sets: "3", reps: "15", rest: "60", intensity: "RPE 7", progression: "保持肘部抬起" },
  ],
  臀腿: [
    { name: "杠铃深蹲", weight: "70", sets: "4", reps: "8", rest: "120", intensity: "RPE 8", progression: "稳定深度后加重" },
    { name: "罗马尼亚硬拉", weight: "60", sets: "4", reps: "10", rest: "120", intensity: "RPE 8", progression: "先守住髋主导发力" },
    { name: "保加利亚分腿蹲", weight: "20", sets: "3", reps: "10", rest: "75", intensity: "RPE 8", progression: "双侧完成度一致再上调" },
    { name: "坐姿髋外展", weight: "40", sets: "3", reps: "15", rest: "60", intensity: "RPE 7", progression: "顶峰停顿后再慢慢还原" },
  ],
};

export const voiceExerciseAliases: Record<string, string> = {
  绳索引拉: "宽握下拉",
  引拉: "宽握下拉",
  绳索下拉: "宽握下拉",
  高位下拉: "宽握下拉",
  宽拉: "宽握下拉",
  宽握拉: "宽握下拉",
  背阔下拉: "宽握下拉",
  单臂下拉: "单臂绳索下拉",
  单臂绳索下拉: "单臂绳索下拉",
  单边下拉: "单臂绳索下拉",
  窄握拉: "窄握下拉",
  对握拉: "对握下拉",
  下拉: "宽握下拉",
  平板卧推: "平板杠铃卧推",
  杠铃卧推: "平板杠铃卧推",
  卧推: "平板杠铃卧推",
  上斜卧推: "上斜杠铃卧推",
  上斜杠铃: "上斜杠铃卧推",
  上斜哑铃: "上斜哑铃卧推",
  哑铃平板卧推: "哑铃卧推",
  哑铃卧推: "哑铃卧推",
  推胸: "器械推胸",
  器械推胸: "器械推胸",
  飞鸟: "反向飞鸟",
  后束飞鸟: "反向飞鸟",
  推肩: "哑铃推肩",
  哑铃推肩: "哑铃推肩",
  肩推: "器械推肩",
  器械肩推: "器械推肩",
  侧平举: "哑铃侧平举",
  绳索侧平举: "绳索侧平举",
  面拉: "面拉",
  划船: "坐姿划船",
  坐姿划船: "坐姿划船",
  器械划船: "器械划船",
  引体: "引体向上",
  引体向上: "引体向上",
  深蹲: "杠铃深蹲",
  杠铃深蹲: "杠铃深蹲",
  史密斯深蹲: "史密斯深蹲",
  腿举: "腿举",
  分腿蹲: "保加利亚分腿蹲",
  保加利亚: "保加利亚分腿蹲",
  腿弯举: "坐姿腿弯举",
  腿屈伸: "坐姿腿屈伸",
  硬拉: "罗马尼亚硬拉",
  罗马尼亚硬拉: "罗马尼亚硬拉",
  单腿硬拉: "单腿罗马尼亚硬拉",
  臀桥: "臀桥",
  髋外展: "坐姿髋外展",
  坐姿髋外展: "坐姿髋外展",
};

export const voiceMuscleKeywords = [
  { muscle: "胸" as const, keywords: ["胸部", "胸肌", "练胸", "胸"] },
  { muscle: "肩" as const, keywords: ["肩部", "肩膀", "练肩", "肩"] },
  { muscle: "背" as const, keywords: ["背部", "背阔", "练背", "背"] },
  { muscle: "臀腿" as const, keywords: ["臀腿", "腿部", "下肢", "练腿", "臀", "腿"] },
];
